apiVersion: v1
kind: Service
metadata:
  name: parent-bot
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: backend

---
apiVersion: v1
kind: Service
metadata:
  name: child-bot
spec:
  ports:
    - port: 81
      protocol: TCP
  selector:
    app: backend
